---

- name: Install required packages for munin (RedHat).
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ munin_install_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Install required packages for munin (Debian).
  apt: "name={{ item }} state=present"
  with_items: "{{ munin_install_packages }}"
  when: ansible_os_family == 'Debian'
