---

# - debug: var=ansible_default_ipv4.address
# - fail: msg="breakpoint!"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Validate role inputs.
  include: validate.yml

- name: Install Munin
  include: install.yml

- name: Configure Munin
  include: configure.yml
